services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meditation_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - path: ./backend/.env
        required: true

volumes:
  postgres_data:
